# ~/.config/starship.toml
format = "\n$username@$hostname [$directory]($style) $git_branch $character"

[character]
success_symbol = "[\u276f](green)"
error_symbol = "[\u2717](red)"

[directory]
truncation_length = 3
style = "cyan"

[git_branch]
symbol = "ğŸŒ¿ "
style = "bold yellow"

[git_status]
disabled = false
style = "bold red"
ahead = "â‡¡"
behind = "â‡£"
staged = "+"
modified = "!"
conflicted = "âš¡"
deleted = "âœ–"

[python]
symbol = "ğŸ "
style = "bold green"
format = 'via [$symbol$version]($style) '
python_binary = "python3"
disabled = false

[nodejs]
symbol = "îœ˜ "
style = "bold green"
format = 'via [$symbol$version]($style) '
disabled = false

[package]
symbol = "ğŸ“¦ "
style = "dimmed yellow"
format = '[$symbol$version]($style) '
disabled = false

[docker_context]
symbol = "ğŸ³ "
style = "blue bold"
format = '[$symbol$context]($style) '
only_with_files = false
disabled = false

[ssh]
symbol = "ğŸŒ "
style = "bold green"
disabled = false
