# ~/.config/starship.toml
format = "\n$username@$hostname [$directory]($style) $git_branch $character"

# The [character] module, which shows at the end of the prompt.
[character]
success_symbol = "[â¯](bold green)" # The symbol to use for a successful command
error_symbol = "[âœ–](bold red)"   # The symbol for a failed command

[directory]
truncation_length = 3
style = "cyan"

[git_branch]
symbol = "ğŸŒ¿ "
style = "bold yellow"

[git_status]
disabled = false
style = "bold red"
ahead = "â‡¡"
behind = "â‡£"
staged = "+"
modified = "!"
conflicted = "âš¡"
deleted = "âœ–"

[python]
symbol = "ğŸ "
style = "bold green"
format = 'via [$symbol$version]($style) '
python_binary = "python3"
disabled = false

[nodejs]
symbol = "îœ˜ "
style = "bold green"
format = 'via [$symbol$version]($style) '
disabled = false

[package]
symbol = "ğŸ“¦ "
style = "dimmed yellow"
format = '[$symbol$version]($style) '
disabled = false

[docker_context]
symbol = "ğŸ³ "
style = "blue bold"
format = '[$symbol$context]($style) '
only_with_files = false
disabled = false

[hostname]
ssh_only = true
ssh_symbol = "ğŸŒ "
style = "bold green"
disabled = false
